### ISSUE TITLE
small problem

### ISSUE THREAD

**Issue by emoop** [etiennetremel/Class-WooCommerce-Product-Importer#1]
Hi,Your Class-WooCommerce-Product-Importer is great job,but small piece of code dont work for me.This variable '$term' is being used without any value assigned, could you tell me what is its purpose.
  'slug'  => sanitize_title( $term ) in  public function add_variation_to_product( $product_id, $args ).
Variation data,like price,stock don't save..Please help me.

**Comment by etiennetremel** [comment]
Hi emoop, you are right, $term should be $variation_name, I just fixed it:

https://github.com/etiennetremel/Class-WooCommerce-Product-Importer/commit/9382a2a50f52b520eabdaab2e599d2cc6c3b9b03#diff-ea533796e0a62670a3ea0aa7199bd382

Thank you for noticing me.
